title: Wenxin Fang   # your title
author: Wenxin Fang # your name
description: Corner for thoughts and ideas # your description
avatar: /images/vietnam.jpg
 # change avatar

# Build Settings
markdown: kramdown
highlighter: rouge

# Pagination
paginate: 5
paginate_path: "/page:num/"
gems: [jekyll-paginate]

# Comments
# disqus:
#   shortname: xxxx-xxxxx-xxx   # your disqus shortname

# Google Analytics
# google_analytics: xx-xxxxxxxx-1  # your google analytics
